# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from obstacle_recognizer/Information.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Information(genpy.Message):
  _md5sum = "e0cabc38676e4b76862576a407bfef61"
  _type = "obstacle_recognizer/Information"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 latitude
float64 longitude
float64 x
float64 y
float64 radius
float64 yaw
float64 velocity
float64 velocity_x
float64 velocity_y"""
  __slots__ = ['latitude','longitude','x','y','radius','yaw','velocity','velocity_x','velocity_y']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,x,y,radius,yaw,velocity,velocity_x,velocity_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Information, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.radius is None:
        self.radius = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.velocity_x is None:
        self.velocity_x = 0.
      if self.velocity_y is None:
        self.velocity_y = 0.
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.x = 0.
      self.y = 0.
      self.radius = 0.
      self.yaw = 0.
      self.velocity = 0.
      self.velocity_x = 0.
      self.velocity_y = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.latitude, _x.longitude, _x.x, _x.y, _x.radius, _x.yaw, _x.velocity, _x.velocity_x, _x.velocity_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.latitude, _x.longitude, _x.x, _x.y, _x.radius, _x.yaw, _x.velocity, _x.velocity_x, _x.velocity_y,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.latitude, _x.longitude, _x.x, _x.y, _x.radius, _x.yaw, _x.velocity, _x.velocity_x, _x.velocity_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.latitude, _x.longitude, _x.x, _x.y, _x.radius, _x.yaw, _x.velocity, _x.velocity_x, _x.velocity_y,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_9d = struct.Struct("<9d")
